Update: Built API
GDGVIT/song-story-backend pull request #3
Opened 2020-06-27 11:32 UTC by ramaneswaran

2020-07-02 09:45 UTC, Geek-ubaid requested changes

2020-07-02 09:45 UTC, Geek-ubaid commented on app/genius/__init__.py
> +            query = '%20'.join(query.split(' '))
use urlencode for making query param string

2020-07-02 10:38 UTC, ramaneswaran commented on app/genius/__init__.py
> +            query = '%20'.join(query.split(' '))
All right will do, tbh i didn't know urlencode existed

2020-07-04 12:08 UTC, Geek-ubaid commented
@ramaneswaran Update the PR with the requested changes its getting stale

2020-07-04 14:44 UTC, ramaneswaran commented
Added urlencode

2020-07-05 12:08 UTC, Geek-ubaid approved these changes

2020-07-05 12:08 UTC, merged